#!/bin/bash

# Execute dev.rfpez.ai deployment test
# This script will guide through manual Chrome browser testing

echo "========================================="
echo "Dev.rfpez.ai Deployment Test Executor"
echo "========================================="
echo ""
echo "Test Scenario: Office Furniture Procurement"
echo "Target: https://dev.rfpez.ai"
echo ""
echo "INSTRUCTIONS:"
echo "1. Open Chrome browser"
echo "2. Navigate to: https://dev.rfpez.ai"
echo "3. Open browser DevTools (F12)"
echo "4. Copy and paste the following commands into the Console"
echo ""
echo "========================================="
echo "Test Credentials:"
echo "Email: mskiba@esphere.com"
echo "Password: thisisatest"
echo "========================================="
echo ""
echo "Press ENTER to see Step 1..."
read

echo ""
echo "========================================="
echo "STEP 1: Navigate and Screenshot"
echo "========================================="
echo "Ensure you are at: https://dev.rfpez.ai"
echo "Take screenshot: 01-homepage.png"
echo ""
echo "Press ENTER to continue to Step 2..."
read

echo ""
echo "========================================="
echo "STEP 2: Login"
echo "========================================="
echo "Run in DevTools Console:"
echo ""
echo "// Click login button"
echo "document.querySelector('[data-testid=\"login-button\"]')?.click();"
echo ""
echo "// Fill email"
echo "document.querySelector('input[type=\"email\"]').value = 'mskiba@esphere.com';"
echo ""
echo "// Fill password"
echo "document.querySelector('input[type=\"password\"]').value = 'thisisatest';"
echo ""
echo "// Submit"
echo "document.querySelector('input[type=\"password\"]').dispatchEvent(new KeyboardEvent('keydown', {key: 'Enter', code: 'Enter', keyCode: 13}));"
echo ""
echo "Wait for login to complete..."
echo "Take screenshot: 02-logged-in.png"
echo ""
echo "Press ENTER to continue to Step 3..."
read

echo ""
echo "========================================="
echo "STEP 3: Create New Session"
echo "========================================="
echo "Run in DevTools Console:"
echo ""
echo "document.querySelector('[data-testid=\"new-session-button\"]')?.click();"
echo ""
echo "Take screenshot: 03-new-session.png"
echo ""
echo "Press ENTER to continue to Step 4..."
read

echo ""
echo "========================================="
echo "STEP 4: Create RFP"
echo "========================================="
echo "Run in DevTools Console:"
echo ""
echo "const messageInput = document.querySelector('[data-testid=\"message-input\"]');"
echo "messageInput.value = 'Create a new RFP for Office Furniture Procurement. Complete office furniture set for new 50-person office space';"
echo "messageInput.dispatchEvent(new Event('input', { bubbles: true }));"
echo "messageInput.dispatchEvent(new KeyboardEvent('keydown', {key: 'Enter', code: 'Enter', keyCode: 13}));"
echo ""
echo "Wait 5-8 seconds for response..."
echo "Take screenshot: 04-rfp-created.png (full page)"
echo ""
echo "Press ENTER to continue to Step 5..."
read

echo ""
echo "========================================="
echo "STEP 5: Generate Specifications"
echo "========================================="
echo "Run in DevTools Console:"
echo ""
echo "const messageInput = document.querySelector('[data-testid=\"message-input\"]');"
echo "messageInput.value = 'Generate detailed technical specifications including: Executive desks (10 units), Standard workstations (40 units), Conference tables (3 units), Office chairs - ergonomic (50 units), Filing cabinets (15 units). Requirements: BIFMA certified furniture, Warranty minimum 5 years, Delivery within 6 weeks, Installation included';"
echo "messageInput.dispatchEvent(new Event('input', { bubbles: true }));"
echo "messageInput.dispatchEvent(new KeyboardEvent('keydown', {key: 'Enter', code: 'Enter', keyCode: 13}));"
echo ""
echo "Wait 8-10 seconds for response..."
echo "Take screenshot: 05-specifications-generated.png (full page)"
echo ""
echo "Press ENTER to continue to Step 6..."
read

echo ""
echo "========================================="
echo "STEP 6: Create Bid Form"
echo "========================================="
echo "Run in DevTools Console:"
echo ""
echo "const messageInput = document.querySelector('[data-testid=\"message-input\"]');"
echo "messageInput.value = 'Create a bid submission form for suppliers to respond to this RFP';"
echo "messageInput.dispatchEvent(new Event('input', { bubbles: true }));"
echo "messageInput.dispatchEvent(new KeyboardEvent('keydown', {key: 'Enter', code: 'Enter', keyCode: 13}));"
echo ""
echo "Wait 6-8 seconds for response..."
echo "Take screenshot: 06-bid-form-created.png (full page)"
echo ""
echo "Press ENTER to continue to Step 7..."
read

echo ""
echo "========================================="
echo "STEP 7: Generate RFP Email"
echo "========================================="
echo "Run in DevTools Console:"
echo ""
echo "const messageInput = document.querySelector('[data-testid=\"message-input\"]');"
echo "messageInput.value = 'Generate an RFP announcement email to send to potential suppliers';"
echo "messageInput.dispatchEvent(new Event('input', { bubbles: true }));"
echo "messageInput.dispatchEvent(new KeyboardEvent('keydown', {key: 'Enter', code: 'Enter', keyCode: 13}));"
echo ""
echo "Wait 5-7 seconds for response..."
echo "Take screenshot: 07-rfp-email-generated.png (full page)"
echo ""
echo "Press ENTER to continue to Step 8..."
read

echo ""
echo "========================================="
echo "STEP 8: Add First Supplier Bid"
echo "========================================="
echo "Supplier: Premier Office Solutions"
echo "Bid: \$125,000"
echo ""
echo "Run in DevTools Console:"
echo ""
echo "const messageInput = document.querySelector('[data-testid=\"message-input\"]');"
echo "messageInput.value = 'Record a bid from Premier Office Solutions: Total bid \$125,000, Delivery: 4 weeks, Warranty: 7 years. Notes: Includes white-glove installation and 2-year maintenance';"
echo "messageInput.dispatchEvent(new Event('input', { bubbles: true }));"
echo "messageInput.dispatchEvent(new KeyboardEvent('keydown', {key: 'Enter', code: 'Enter', keyCode: 13}));"
echo ""
echo "Wait 4-5 seconds for response..."
echo "Take screenshot: 08-first-bid-recorded.png (full page)"
echo ""
echo "Press ENTER to continue to Step 9..."
read

echo ""
echo "========================================="
echo "STEP 9: Add Second Supplier Bid"
echo "========================================="
echo "Supplier: Corporate Workspace Inc"
echo "Bid: \$118,000"
echo ""
echo "Run in DevTools Console:"
echo ""
echo "const messageInput = document.querySelector('[data-testid=\"message-input\"]');"
echo "messageInput.value = 'Record a bid from Corporate Workspace Inc: Total bid \$118,000, Delivery: 5 weeks, Warranty: 5 years. Notes: Volume discount applied, standard installation included';"
echo "messageInput.dispatchEvent(new Event('input', { bubbles: true }));"
echo "messageInput.dispatchEvent(new KeyboardEvent('keydown', {key: 'Enter', code: 'Enter', keyCode: 13}));"
echo ""
echo "Wait 4-5 seconds for response..."
echo "Take screenshot: 09-second-bid-recorded.png (full page)"
echo ""
echo "Press ENTER to continue to Step 10..."
read

echo ""
echo "========================================="
echo "STEP 10: Add Third Supplier Bid"
echo "========================================="
echo "Supplier: Modern Office Outfitters"
echo "Bid: \$135,000"
echo ""
echo "Run in DevTools Console:"
echo ""
echo "const messageInput = document.querySelector('[data-testid=\"message-input\"]');"
echo "messageInput.value = 'Record a bid from Modern Office Outfitters: Total bid \$135,000, Delivery: 3 weeks, Warranty: 10 years. Notes: Premium furniture line, expedited delivery, extended warranty';"
echo "messageInput.dispatchEvent(new Event('input', { bubbles: true }));"
echo "messageInput.dispatchEvent(new KeyboardEvent('keydown', {key: 'Enter', code: 'Enter', keyCode: 13}));"
echo ""
echo "Wait 4-5 seconds for response..."
echo "Take screenshot: 10-third-bid-recorded.png (full page)"
echo ""
echo "Press ENTER to continue to Step 11..."
read

echo ""
echo "========================================="
echo "STEP 11: Create Bid Comparison"
echo "========================================="
echo "Run in DevTools Console:"
echo ""
echo "const messageInput = document.querySelector('[data-testid=\"message-input\"]');"
echo "messageInput.value = 'Create a comparison table of all received bids with recommendations';"
echo "messageInput.dispatchEvent(new Event('input', { bubbles: true }));"
echo "messageInput.dispatchEvent(new KeyboardEvent('keydown', {key: 'Enter', code: 'Enter', keyCode: 13}));"
echo ""
echo "Wait 6-8 seconds for response..."
echo "Take screenshot: 11-bid-comparison.png (full page)"
echo ""
echo "Press ENTER to continue to Step 12..."
read

echo ""
echo "========================================="
echo "STEP 12: Final State"
echo "========================================="
echo "Take final screenshot: 12-final-state.png (full page)"
echo ""
echo "========================================="
echo "VALIDATION CHECKLIST"
echo "========================================="
echo ""
echo "Check the following:"
echo "[ ] RFP created: 'Office Furniture Procurement'"
echo "[ ] Technical specifications generated"
echo "[ ] Bid form created"
echo "[ ] RFP email generated"
echo "[ ] 3 supplier bids recorded"
echo "[ ] Bid comparison table created"
echo "[ ] No console errors"
echo "[ ] All artifacts visible in artifact panel"
echo "[ ] RFP context shown in footer"
echo ""
echo "========================================="
echo "TEST COMPLETE"
echo "========================================="
echo ""
echo "Review all screenshots and validation checklist."
echo "Report any issues or errors encountered."
echo ""
