-- Migration: Update embedding dimensions from 384 to 768
-- Purpose: Support paraphrase-multilingual-mpnet-base-v2 model (768 dimensions)
-- This is a local model running via Transformers.js - no API calls required

BEGIN;

-- Ensure pgvector extension is enabled in extensions schema
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA extensions;

-- Drop existing embeddings (will be regenerated with new dimensions)
UPDATE public.account_memories 
SET embedding = NULL 
WHERE memory_type = 'knowledge';

-- Drop the existing index before changing vector dimensions
DROP INDEX IF EXISTS idx_account_memories_embedding;

-- Update the embedding column type to 768 dimensions
-- Use extensions.vector to reference the vector type from the extensions schema
ALTER TABLE public.account_memories 
  ALTER COLUMN embedding TYPE extensions.vector(768);

-- Recreate the index with new vector dimensions
CREATE INDEX IF NOT EXISTS idx_account_memories_embedding 
  ON public.account_memories 
  USING hnsw (embedding extensions.vector_cosine_ops);

-- Add comment explaining the dimension change
COMMENT ON COLUMN public.account_memories.embedding IS 
  'Semantic embedding vector (768 dimensions) - Generated by paraphrase-multilingual-mpnet-base-v2 model (local, no API)';

COMMIT;

-- Note: You'll need to regenerate embeddings for existing knowledge base entries
-- Run: node scripts/load-knowledge-base.js
