-- Migration: Update embedding dimensions from 384 to 768
-- Purpose: Support paraphrase-multilingual-mpnet-base-v2 model (768 dimensions)
-- This is a local model running via Transformers.js - no API calls required

BEGIN;

-- Drop existing embeddings (will be regenerated with new dimensions)
UPDATE public.account_memories 
SET embedding = NULL 
WHERE memory_type = 'knowledge';

-- Update the embedding column type to 768 dimensions
ALTER TABLE public.account_memories 
  ALTER COLUMN embedding TYPE vector(768);

-- Add comment explaining the dimension change
COMMENT ON COLUMN public.account_memories.embedding IS 
  'Semantic embedding vector (768 dimensions) - Generated by paraphrase-multilingual-mpnet-base-v2 model (local, no API)';

COMMIT;

-- Note: You'll need to regenerate embeddings for existing knowledge base entries
-- Run: node scripts/load-knowledge-base.js
